### PR TITLE
json_api serializer now access camel case fields correctly

### PR DESCRIPTION
**Pull request by dalefukami**
This functionality was working in beta 22 but started failing in beta 23.

I had problems getting the browserify tests to run on my machine and wasn't sure if I was just missing dependencies or what.

### CODE REVIEW

**Comment by 0x8890** [comment]
Looks good! :+1: 

Don't worry about the browser tests, serializers aren't included in the browser build anyways. Also FYI, ff you don't have Firefox installed it won't run.

**Comment by dalefukami** [comment]
Would it be possible to get a version bump for this?

**Comment by 0x8890** [comment]
yes, when I get home :)

**Comment by 0x8890** [comment]
Done, published as `1.0.0-beta.31`. You're [credited in the changelog](http://fortunejs.com/changelog/) :)

**Pull request merged**
