### PR TITLE
Add options to create, update, delete methods

### PR DESCRIPTION
**Pull request by repl-andrew-ovens**

### CODE REVIEW

**Comment by 0x8890** [comment]
It doesn't make sense to add `options` to the `create` method, and the update format doesn't suit options either:
```js
{ id, replace, push, pull, operate }
```
It's intended to be oversimplified so that none of the methods accept options except for find. Otherwise if you have a use case for this, perhaps work with the database directly.

**Comment by avens19** [comment]
We are actually using FortuneJS as a middleware technology and therefore require the options hash to access headers to forward auth cookies etc.

**Comment by repl-andrew-ovens** [comment]
Oops, commented with my personal account, either way, that was the reason we needed the options hash

**Comment by 0x8890** [comment]
Hmm, I see. Is there any reason why in-band communication is not an option? Suppose there is a `cookie` field on the record:
```js
{ id, cookie, ... }
```

**Comment by repl-andrew-ovens** [comment]
Uh mostly that it would muddy all our types/models and it's a bit awkward to do through ember-data

**Comment by 0x8890** [comment]
Could be just done through the `transform` function:
```js
.transformInput((context, record, update) => {
  const { request: { meta, method } } = context
  if (method === methods.create) {
    record.cookie = meta.cookie
    return record
  }
  return update
})
```

**Comment by repl-andrew-ovens** [comment]
Hmm alright, thanks :)

**Comment by dalefukami** [comment]
@0x8890 , we've looked into the transformInput suggestion but the delete method doesn't actually act on records it only has ids so I'm not sure this strategy is going to work particularly well. I think it's possible that we haven't quite explained some of the use cases very well and perhaps we're solving this problem the wrong way. I'll give it another try with a different example. We'd appreciate your thoughts on how we might solve our problem.

Essentially, we have some information that changes per request that is required by the adapter. Since the adapter is a singleton this is proving difficult to do so we thought passing things along in the options hash would be the most effective way of doing this. It has worked for us so far in the find method.

As an Example, we host our tenants in separate postgresql schemas. For each request the adapter needs to know which tenant the request is for so it can reference the correct table.

Getting the information on a per request basis is easy enough in the serializers, or via transformInput as suggested, but ensuring that this information reaches the adapter in all the various methods is the part we're trying to solve with this pull request.

Does this example make sense? Any thoughts on how we might achieve this with the current structure or possible direction we could take that might fit in better with how you'd like fortunejs to support something like this? We're happy to do the dev work to create a pull request. Just want to make sure we're in line with your vision of the project.

Thanks for the help so far!

**Comment by 0x8890** [comment]
@dalefukami another idea is that you can assign properties to the `ids` associative array.

For example, if this request is made:

```js
const ids = [ ... ] // just an array of IDs
ids.customProperty = 'foobar'
store.request({ type, ids, method: delete })
```

The `customProperty` key gets forwarded all the way to the adapter. To do this, you could subclass a serializer like so:

```js
class CustomSerializer extends JsonApiSerializer {
  processRequest (context, request, response) {
    return super.processRequest(...arguments)
    .then(context => {
      if (context.request.ids)
        context.request.ids.customProperty = request.headers['cookie']
      return context
    })
  }
}
```

I hope that solution is viable for your use case.

**Comment by dalefukami** [comment]
Hmm. We started down the path you've suggested a bit but are running into issues based on the fact that this just isn't baked into the library.

For example, this line calls an adapter find method while checking the referential integrity of a relationship field. Unfortunately, any options or custom meta data that we've set will never get passed through to the adapter because we have no control over this call.
https://github.com/fortunejs/fortune/blob/master/lib/dispatch/check_links.js#L21

Another example of a similar issue here in the json_api serializer:
https://github.com/fortunejs/fortune-json-api/blob/master/lib/helpers.js#L80

Any other thoughts?

**Comment by 0x8890** [comment]
OK I think at this point I will agree with you on adding an additional argument to each adapter method. Here's how I think it should be done:

- There's the `meta` object which is a bit unspecified per request. This object gets passed as an additional argument to the adapter method on every call. 
- Serializers will be updated to reflect this change.

This change can be pushed as `1.1.0` since it's a new feature. What do you think?

**Comment by dalefukami** [comment]
That'd work for us!

We can start working through this on our end and submit something to you for review if you'd like. Perhaps you can provide a quick clarification on the new signature of the adapter calls. I'm envisioning something like this:

create(type, records, [meta])
find(type, [id], [options], [meta])
update(type, updates, [meta])
delete(type, [ids], [meta])

**Comment by 0x8890** [comment]
Looks good :+1:

**Comment by repl-andrew-ovens** [comment]
Just to confirm, are you OK with me passing the request.meta object from
the dispatchers by default into this meta parameter and then people will
have the option to override it by extending the serializer?

**Comment by 0x8890** [comment]
Not sure I understand the question, but my idea is that the `request.meta` object just gets added as a last argument in every adapter call.

**Comment by avens19** [comment]
That was my question, sorry for the poor wording. Thanks

**Pull request closed without merging**
