### PR TITLE
[WIP] Fix sort support in JSON API serializer

### PR DESCRIPTION
**Pull request by nickschot**
The JSON API states that sort=param means ascending and sort=-param means descending. Current implementation had support for explicit querying for asc/desc with + or -.

For some (currently to me unknown) reason, Fortune only gives back ascending data no matter the parameter stating asc or desc.

More info: http://jsonapi.org/format/#fetching-sorting

### CODE REVIEW

**Comment by nickschot** [comment]
If you're OK with this change, I'll update the tests too.

**Comment by 0x8890** [comment]
I implemented the JSON API serializer soon after it hit 1.0, maybe the backtracked on this or something or I misread, but at some point in time, the spec did explicitly require `+`. Also I think there's another unrelated problem: I changed the adapter spec so that `sort` requires boolean value instead of `-1` or `1`. I will investigate a fix.

**Comment by nickschot** [comment]
Excellent!

**Comment by 0x8890** [comment]
Fixed in commit `61e83ae7bdcac4f11e4b60107d8c8a1d01ace8e2`.

**Comment by nickschot** [comment]
:+1:

**Pull request closed without merging**
