### PR TITLE
Fix pluralization for relationship types in JSON API serializer

### PR DESCRIPTION
**Pull request by nickschot**
See #86

### CODE REVIEW

**Comment by 0x8890** [comment]
Thanks for the PR!

(Babel seems to be having problems, merged anyways since it looks good)

**Comment by nickschot** [comment]
Yeah, I had the same problems locally. Looks like it needs to be fixed at Babels side of things.

**Comment by 0x8890** [comment]
I [updated the tests](31822ce118181805d6813311a7ccc3f1792cc812) as well, your changes are now published.

**Comment by nickschot** [comment]
Awesome! Thanks for the quick responses. You got yourself a new contributor. Love the project!

**Pull request merged**
